### ISSUE TITLE
Hi, Do you have any plan to upload the pretrain model?

### ISSUE THREAD

**Issue by kevin5645218** [YCHang686/A-CubeNet#1]

**Comment by YCHang686** [comment]
Sorry for late response. We have uploaded all the pretrain models on [https://drive.google.com/file/d/14fqRjc4p-THgvLUJiZkLTJBpqM41kUYM/view?usp=sharing](https://drive.google.com/file/d/14fqRjc4p-THgvLUJiZkLTJBpqM41kUYM/view?usp=sharing)
